name: Snyk

on:
  push:
    branches: [ main ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ main ]
  schedule:
    - cron: '31 10 * * 0'

permissions:
  contents: read

jobs:
  snyk:
    name: Snyk
    runs-on: ubuntu-latest
    steps:
      - uses: step-security/harden-runner@6d3c2fe731c8f225990c8018cb71c337c0d9dfcd
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.snyk.io:443
            github.com:443
            proxy.golang.org:443

      - uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/golang@d406fd286b663eb8c6f8adcced4f7bcd199c0a3f
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
